### ISSUE TITLE
Division by Zero Stacktrace

### ISSUE THREAD

**Issue by simonbethke** [vbousquet/vpx_lightmapper#4]
Here is another one. That happened when batchprocessing the sample-table of VPX.
```
Python: Traceback (most recent call last):
  File "C:\Users\simon\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\vpx_lightmapper\__init__.py", line 382, in execute
    vlm_baker.render_all_groups(self, context)
  File "C:\Users\simon\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\vpx_lightmapper\vlm_baker.py", line 504, in render_all_groups
    state, restore_func = setup_light_scenario(context, scenario, group_mask)
  File "C:\Users\simon\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\vpx_lightmapper\vlm_baker.py", line 400, in setup_light_scenario
    influence = get_light_influence(scenario[2], group_mask)
  File "C:\Users\simon\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\vpx_lightmapper\vlm_baker.py", line 332, in get_light_influence
    alpha_y = light_yr / light_xr
ZeroDivisionError: float division by zero

location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Users\simon\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\vpx_lightmapper\__init__.py", line 382, in execute
    vlm_baker.render_all_groups(self, context)
  File "C:\Users\simon\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\vpx_lightmapper\vlm_baker.py", line 504, in render_all_groups
    state, restore_func = setup_light_scenario(context, scenario, group_mask)
  File "C:\Users\simon\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\vpx_lightmapper\vlm_baker.py", line 400, in setup_light_scenario
    influence = get_light_influence(scenario[2], group_mask)
  File "C:\Users\simon\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\vpx_lightmapper\vlm_baker.py", line 332, in get_light_influence
    alpha_y = light_yr / light_xr
ZeroDivisionError: float division by zero

location: <unknown location>:-1
```

**Comment by vbousquet** [comment]
Fixed by https://github.com/vbousquet/vpx_lightmapper/commit/1a80b53500091db803a70fbf3a5e1655fb9fac2c
